on: [push, pull_request]
name: Continuous Integration

jobs:
  build:
    name: Build and Test codebase

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install GhostScript
      run: |
        sudo apt-get update && \
        sudo apt-get -y install ghostscript

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint
        python -m pip install pytest
        if [ -f requirements_nocuda.txt ]; then pip install --extra-index-url https://repos.knox.cs.aau.dk/ -r requirements_nocuda.txt; fi

    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')

    - name: Test
      run: |
        python -m pytest