on: [push, pull_request]
name: Continuous Integration

jobs:
  build:
    name: pylint_and_pytest

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install pytest
        if [ -f requirements.txt ]; then pip install --extra-index-url https://repos.knox.cs.aau.dk/ -r requirements.txt; fi

    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`

    - name: Run tests
      run: pytest
